name: Deploy Worker

on:
  push:
    branches: [ main, feature/setup-cloudflare ]
  pull_request:
    branches: [ main, feature/setup-cloudflare ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Deploy to cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy

